export const SET_METRIC_VALS = 'SET_METIC_VALS';
export const SET_CASING_PRESSURE = 'SET_CASING_PRESSURE';
export const SET_INJ_VALVE_OPEN = 'SET_INJ_VALVE_OPEN';
export const SET_TUBING_PRESSURE = 'SET_TUBING_PRESSURE';
export const SET_FLARE_TEMP = 'SET_FLARE_TEMP';
export const SET_OIL_TEMP = 'SET_OIL_TEMP';
export const SET_WATER_TEMP = 'SET_WATER_TEMP';
